server:
  port: 9040
  servlet:
    context-path: /admin



gem:
  #
  #  min: 0.01
  #  max: 999
  #  desc: 这是自定义配置，最小值${gem.min},最大值${gem.max}
  #  outPut: asb
  security:
    open: true
    login-page: /login
    error-page: /error
    denied-page: /403
    nofound-page: /404
    index-page: /index


  redis:
    open: true

  swagger:
    web-package-path: com.gemframework.controller

  system:
    min: 2
    max: 22
    desc: xxdd
    generate-code-server-path: /app


spring:
  jpa:
    # 是否打印sql
    show-sql: false
    generate-ddl: false
    hibernate:
      # 开启自动建表功能，一般选update，每次启动会对比实体和数据表结构是否相同，不相同会更新
      ddl-auto: update
      format_sql: true
    # 设置创表引擎为Innodb，不然默认为MyiSam
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://localhost:3306/pearl?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.73,192.168.163.1
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: true
        # 登录名
    #        login-username: admin
    #        # 登录密码
    #        login-password: 123456

    #初始化数据库表配置
    platform: mysql
    #启动时需要初始化的建表语句
    #schema: classpath:schema-mysql.sql
    #初始化的数据
    data: classpath:gem-mysql.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    #schema-password:
    #schema-username:
    data-username: root
    data-password: 123456
    sql-script-encoding: utf-8
    separator: ;

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 30000


  #  mvc:
  #    view:
  #      prefix: classpath:/templates/pages/
  #      suffix: .html

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: true #开启热部署
      additional-paths: src/main/java
#      exclude: static/**,public/**

